site_name: test
plugins:
    - wavedrom:

nav:
    - 'README.md'
    - 'test.md'

extra_javascript:
    # use local.
    # - wavedrom.unpkg.js
    # - skin-default.js
    # from internet.
    - https://cdn.jsdelivr.net/npm/wavedrom@3.1.0/wavedrom.min.js
    - https://wavedrom.com/skins/default.js

